insert into EQUIPMENT (EQUIPMENT_NAME,EQUIPMENT_TYPE,EQUIPMENT_BRAND,EQUIPMENT_DESCRIPTION, EQUIPMENT_ENTRYUSER) values ('Blue Wrench','Wrench','Altendorf','A blue wrench','Bob' );
insert into EQUIPMENT (EQUIPMENT_NAME,EQUIPMENT_TYPE,EQUIPMENT_BRAND,EQUIPMENT_DESCRIPTION, EQUIPMENT_ENTRYUSER) values ('Red Wrench','Wrench','Crescent','A blue wrench','Bob' );
insert into EQUIPMENT (EQUIPMENT_NAME,EQUIPMENT_TYPE,EQUIPMENT_BRAND,EQUIPMENT_DESCRIPTION, EQUIPMENT_ENTRYUSER) values ('Yellow Wrench','Wrench','Fein','A blue wrench','Bob' );
insert into EQUIPMENT (EQUIPMENT_NAME,EQUIPMENT_TYPE,EQUIPMENT_BRAND,EQUIPMENT_DESCRIPTION, EQUIPMENT_ENTRYUSER) values ('Purple Wrench','Wrench','Dynamic','A blue wrench','Bob' );
insert into EQUIPMENT (EQUIPMENT_NAME,EQUIPMENT_TYPE,EQUIPMENT_BRAND,EQUIPMENT_DESCRIPTION, EQUIPMENT_ENTRYUSER) values ('Green Wrench','Wrench','Pittsburgh Tools','A blue wrench','Bob' );
insert into EQUIPMENT (EQUIPMENT_NAME,EQUIPMENT_TYPE,EQUIPMENT_BRAND,EQUIPMENT_DESCRIPTION, EQUIPMENT_ENTRYUSER) values ('Orange Wrench','Wrench','US General','A blue wrench','Bob' );
insert into EQUIPMENT (EQUIPMENT_NAME,EQUIPMENT_TYPE,EQUIPMENT_BRAND,EQUIPMENT_DESCRIPTION, EQUIPMENT_ENTRYUSER) values ('Cyan Wrench','Wrench','Mafell','A blue wrench','Bob' );
insert into EQUIPMENT (EQUIPMENT_NAME,EQUIPMENT_TYPE,EQUIPMENT_BRAND,EQUIPMENT_DESCRIPTION, EQUIPMENT_ENTRYUSER) values ('Pink Wrench','Wrench',' Chicago Tools','A blue wrench','Bob' );
insert into EQUIPMENT (EQUIPMENT_NAME,EQUIPMENT_TYPE,EQUIPMENT_BRAND,EQUIPMENT_DESCRIPTION, EQUIPMENT_ENTRYUSER) values ('Grey Wrench','Wrench','Veritas','A blue wrench','Bob' );
insert into EQUIPMENT (EQUIPMENT_NAME,EQUIPMENT_TYPE,EQUIPMENT_BRAND,EQUIPMENT_DESCRIPTION, EQUIPMENT_ENTRYUSER) values ('Small Wrench','Wrench','Cen Tech','A blue wrench','John' );
insert into EQUIPMENT (EQUIPMENT_NAME,EQUIPMENT_TYPE,EQUIPMENT_BRAND,EQUIPMENT_DESCRIPTION, EQUIPMENT_ENTRYUSER) values ('Large Wrench','Wrench','Central Machinery','A blue wrench','John' );
insert into EQUIPMENT (EQUIPMENT_NAME,EQUIPMENT_TYPE,EQUIPMENT_BRAND,EQUIPMENT_DESCRIPTION, EQUIPMENT_ENTRYUSER) values ('Medium Wrench','Wrench','Pittsburgh Tools','A blue wrench','John' );
insert into EQUIPMENT (EQUIPMENT_NAME,EQUIPMENT_TYPE,EQUIPMENT_BRAND,EQUIPMENT_DESCRIPTION, EQUIPMENT_ENTRYUSER) values ('Magic Wrench','Wrench',' Chicago Tools','A blue wrench','John' );
insert into EQUIPMENT (EQUIPMENT_NAME,EQUIPMENT_TYPE,EQUIPMENT_BRAND,EQUIPMENT_DESCRIPTION, EQUIPMENT_ENTRYUSER) values ('Blue Screwdriver','Screwdriver','Toyota','A blue Screwdriver','John' );
insert into EQUIPMENT (EQUIPMENT_NAME,EQUIPMENT_TYPE,EQUIPMENT_BRAND,EQUIPMENT_DESCRIPTION, EQUIPMENT_ENTRYUSER) values ('Red Screwdriver','Screwdriver','Hitachi','A red Screwdriver','John' );
insert into EQUIPMENT (EQUIPMENT_NAME,EQUIPMENT_TYPE,EQUIPMENT_BRAND,EQUIPMENT_DESCRIPTION, EQUIPMENT_ENTRYUSER) values ('Yellow Screwdriver','Screwdriver','Veritas','A yellow Screwdriver','John' );
insert into EQUIPMENT (EQUIPMENT_NAME,EQUIPMENT_TYPE,EQUIPMENT_BRAND,EQUIPMENT_DESCRIPTION, EQUIPMENT_ENTRYUSER) values ('Purple Screwdriver','Screwdriver','Central Machinery','A purple Screwdriver','Bob' );
insert into EQUIPMENT (EQUIPMENT_NAME,EQUIPMENT_TYPE,EQUIPMENT_BRAND,EQUIPMENT_DESCRIPTION, EQUIPMENT_ENTRYUSER) values ('Green Screwdriver','Screwdriver','Pittsburgh Tools','A green Screwdriver','Bob' );
insert into EQUIPMENT (EQUIPMENT_NAME,EQUIPMENT_TYPE,EQUIPMENT_BRAND,EQUIPMENT_DESCRIPTION, EQUIPMENT_ENTRYUSER) values ('Orange Screwdriver','Screwdriver','Cen Tech','A orange Screwdriver','Bob' );
insert into EQUIPMENT (EQUIPMENT_NAME,EQUIPMENT_TYPE,EQUIPMENT_BRAND,EQUIPMENT_DESCRIPTION, EQUIPMENT_ENTRYUSER) values ('Cyan Screwdriver','Screwdriver',' Chicago Tools','A cyan Screwdriver','Bob' );
insert into EQUIPMENT (EQUIPMENT_NAME,EQUIPMENT_TYPE,EQUIPMENT_BRAND,EQUIPMENT_DESCRIPTION, EQUIPMENT_ENTRYUSER) values ('Pink Screwdriver','Screwdriver','Hitachi','A pink Screwdriver','Bob' );
insert into EQUIPMENT (EQUIPMENT_NAME,EQUIPMENT_TYPE,EQUIPMENT_BRAND,EQUIPMENT_DESCRIPTION, EQUIPMENT_ENTRYUSER) values ('Grey Screwdriver','Screwdriver','Central Machinery','A grey Screwdriver','Bob' );
insert into EQUIPMENT (EQUIPMENT_NAME,EQUIPMENT_TYPE,EQUIPMENT_BRAND,EQUIPMENT_DESCRIPTION, EQUIPMENT_ENTRYUSER) values ('Small Screwdriver','Screwdriver','Cen Tech','A small Screwdriver','Bob' );
insert into EQUIPMENT (EQUIPMENT_NAME,EQUIPMENT_TYPE,EQUIPMENT_BRAND,EQUIPMENT_DESCRIPTION, EQUIPMENT_ENTRYUSER) values ('Large Screwdriver','Screwdriver','US General','A large Screwdriver','Bob' );
insert into EQUIPMENT (EQUIPMENT_NAME,EQUIPMENT_TYPE,EQUIPMENT_BRAND,EQUIPMENT_DESCRIPTION, EQUIPMENT_ENTRYUSER) values ('Medium Screwdriver','Screwdriver','Central Machinery','A medium Screwdriver','Bob' );
insert into EQUIPMENT (EQUIPMENT_NAME,EQUIPMENT_TYPE,EQUIPMENT_BRAND,EQUIPMENT_DESCRIPTION, EQUIPMENT_ENTRYUSER) values ('Magical Screwdriver','Screwdriver','Toyota','A magical Screwdriver','Bob' );